#import <UIKit/UIKit.h>
#import "ResearchUI.h"
#import <objc/runtime.h>
#import "AlwaysOnAudio.h"
@interface TIOAlwaysOnAudioPanel:UITableViewController
@property(nonatomic) NSDictionary *nativeStatus;
@property(nonatomic) NSArray *files;
@property(nonatomic) BOOL busy;
@end
@implementation TIOAlwaysOnAudioPanel
- (void)viewDidLoad{[super viewDidLoad];self.title=@"Always-On Audio";self.navigationItem.rightBarButtonItem=[[UIBarButtonItem alloc]initWithBarButtonSystemItem:UIBarButtonSystemItemRefresh target:self action:@selector(refresh)];[self refresh];}
- (void)refresh{if(self.busy)return;self.nativeStatus=TIOAOStatus();self.busy=YES;dispatch_async(dispatch_get_global_queue(QOS_CLASS_UTILITY,0),^{NSArray *files=TIOAOAudioFiles([NSURL fileURLWithPath:NSHomeDirectory()]);dispatch_async(dispatch_get_main_queue(),^{self.files=files;self.busy=NO;[self.tableView reloadData];});});}
- (void)message:(NSString *)text{UIAlertController *a=[UIAlertController alertControllerWithTitle:@"Always-On Audio" message:text preferredStyle:UIAlertControllerStyleAlert];[a addAction:[UIAlertAction actionWithTitle:@"OK" style:UIAlertActionStyleCancel handler:nil]];[self presentViewController:a animated:YES completion:nil];}
- (NSInteger)numberOfSectionsInTableView:(UITableView *)t{return 2;}
- (NSInteger)tableView:(UITableView *)t numberOfRowsInSection:(NSInteger)s{return s==0?2:MAX(1,(NSInteger)self.files.count);}
- (NSString *)tableView:(UITableView *)t titleForHeaderInSection:(NSInteger)s{return s==0?@"Official Local Audio Saving":@"Saved Audio Copies";}
- (NSString *)tableView:(UITableView *)t titleForFooterInSection:(NSInteger)s{return s==0?@"Saves only audio the official Always-On Notes receives after this is turned on. It doesn't start the mic or notes, and can't recover earlier unsaved audio. Local only, with extra event-body logging off. Leaving it on uses storage, so turn it off when done; files are never auto-deleted. Recheck the switch after the app restarts.":@"Stop the current Always-On Notes session in the official app first, then refresh and pick a file to share. Only the official notes debug sessions folder is listed, without mock input or Subtitles audio. Realtime and cached files may be different segments; they aren't merged and may have gaps. PCM is raw audio and won't play as WAV.";}
- (UITableViewCell *)tableView:(UITableView *)t cellForRowAtIndexPath:(NSIndexPath *)ip{UITableViewCell *c=[[UITableViewCell alloc]initWithStyle:UITableViewCellStyleSubtitle reuseIdentifier:nil];TIOStyleResearchCell(c);c.detailTextLabel.numberOfLines=0;
    if(ip.section==0&&ip.row==0){c.textLabel.text=@"Save Upcoming Notes Audio";c.detailTextLabel.text=self.nativeStatus?@"Official ASR and Model unchanged; no auto-upload":@"Official version or audio interface not ready";UISwitch *s=[UISwitch new];s.on=[self.nativeStatus[@"dumpEnabled"] boolValue];s.enabled=self.nativeStatus!=nil&&!self.busy;[s addTarget:self action:@selector(toggle:) forControlEvents:UIControlEventValueChanged];c.accessoryView=s;}
    else if(ip.section==0){c.textLabel.text=[self.nativeStatus[@"alwaysOnRunning"] boolValue]?@"Always-On Notes is running; stop it before sharing":@"Always-On Notes is not running";c.detailTextLabel.text=[NSString stringWithFormat:@"Realtime packets: %@ · Cached packets: %@ · %@",self.nativeStatus[@"realtimePackets"]?:@0,self.nativeStatus[@"cachedPackets"]?:@0,self.nativeStatus?@"Official status":@"Interface unavailable"] ;}
    else if(!self.files.count){c.textLabel.text=self.busy?@"Reading…":@"No Saved Audio";c.detailTextLabel.text=@"Turn on saving, use the official Always-On Notes once, stop it, then refresh.";c.selectionStyle=UITableViewCellSelectionStyleNone;}
    else{NSDictionary *r=self.files[ip.row];NSDateFormatter *f=[NSDateFormatter new];f.dateFormat=@"MM-dd HH:mm:ss";c.textLabel.text=[NSString stringWithFormat:@"%@ · %@",r[@"kind"],[f stringFromDate:r[@"date"]]];c.detailTextLabel.text=[NSString stringWithFormat:@"%@ · %@",[(NSURL *)r[@"url"] pathExtension],[NSByteCountFormatter stringFromByteCount:[r[@"bytes"] longLongValue] countStyle:NSByteCountFormatterCountStyleFile]];c.accessoryType=UITableViewCellAccessoryDisclosureIndicator;}return c;
}
- (void)toggle:(UISwitch *)sender{BOOL requested=sender.on;sender.on=[self.nativeStatus[@"dumpEnabled"] boolValue];if(!requested){BOOL ok=TIOAOSetAudioSaving(NO);[self refresh];if(!ok)[self message:@"Turning off couldn't be verified. Check the switch; no audio was deleted. Stopping the official Always-On Notes stops new audio input."];return;}
    UIAlertController *a=[UIAlertController alertControllerWithTitle:@"Save Upcoming Notes Audio?" message:@"When you next use the official Always-On Notes, real conversation audio will also be saved on this phone. Make sure everyone involved has consented. It may use a lot of space. Nothing is uploaded or auto-deleted, and past recordings can't be recovered. This does not start Always-On Notes." preferredStyle:UIAlertControllerStyleAlert];[a addAction:[UIAlertAction actionWithTitle:@"Cancel" style:UIAlertActionStyleCancel handler:nil]];[a addAction:[UIAlertAction actionWithTitle:@"Turn On Local Audio Saving" style:UIAlertActionStyleDefault handler:^(UIAlertAction *x){BOOL ok=TIOAOSetAudioSaving(YES);[self refresh];if(!ok)[self message:@"The setting couldn't be fully verified. Check the switch; you can turn it off manually. Always-On Notes was not started."];else [self message:@"Audio saving is on. Start a short Always-On Notes session in the official app, stop it, then come back and refresh. Earlier unsaved audio won't appear."];}]];[self presentViewController:a animated:YES completion:nil];
}
- (void)tableView:(UITableView *)t didSelectRowAtIndexPath:(NSIndexPath *)ip{[t deselectRowAtIndexPath:ip animated:YES];if(ip.section!=1||self.busy||ip.row>=((NSInteger)self.files.count))return;NSDictionary *s=TIOAOStatus();if(!s||[s[@"alwaysOnRunning"] boolValue]){[self message:@"Stop the official Always-On Notes first, wait for the audio to be written, then refresh and share."];return;}
    if([s[@"dumpEnabled"] boolValue]){[self message:@"Turn off the audio saving switch above first so the official app can finish the file, then refresh and share. Originals are not deleted."];return;}
    NSURL *source=self.files[ip.row][@"url"];self.busy=YES;dispatch_async(dispatch_get_global_queue(QOS_CLASS_UTILITY,0),^{NSError *error=nil;NSURL *copy=TIOAOAudioCopy([NSURL fileURLWithPath:NSHomeDirectory()],source,&error);dispatch_async(dispatch_get_main_queue(),^{self.busy=NO;if(!copy){[self message:error.localizedDescription];return;}UIActivityViewController *share=[[UIActivityViewController alloc]initWithActivityItems:@[copy] applicationActivities:nil];share.popoverPresentationController.sourceView=self.view;share.popoverPresentationController.sourceRect=CGRectMake(self.view.bounds.size.width/2,100,1,1);[self presentViewController:share animated:YES completion:nil];});});
}
@end
static id (*AudioPriorCell)(id,SEL,id,id);
static id (*AudioPriorFooter)(id,SEL,id,NSInteger);
static void (*AudioPriorSelect)(id,SEL,id,id);
static id AudioCell(id self,SEL cmd,id table,NSIndexPath *ip){if(ip.section!=0||ip.row!=2)return AudioPriorCell(self,cmd,table,ip);UITableViewCell *c=[[UITableViewCell alloc]initWithStyle:UITableViewCellStyleSubtitle reuseIdentifier:nil];TIOStyleResearchCell(c);c.textLabel.text=@"Audio Saving & Sharing";c.detailTextLabel.text=@"Official local save switch · Audio after turn-on · AirDrop";c.detailTextLabel.numberOfLines=0;c.accessoryType=UITableViewCellAccessoryDisclosureIndicator;return c;}
static id AudioFooter(id self,SEL cmd,id table,NSInteger s){if(s==0)return @"Text includes only final text saved after you turned it on in the add-on; full official history isn't available yet. Audio uses the official local save interface, must be turned on first, and covers only later sessions, not the full history.";return AudioPriorFooter(self,cmd,table,s);}
static void AudioSelect(id self,SEL cmd,UITableView *t,NSIndexPath *ip){if(ip.section!=0||ip.row!=2){AudioPriorSelect(self,cmd,t,ip);return;}[t deselectRowAtIndexPath:ip animated:YES];[[(UIViewController *)self navigationController] pushViewController:[[TIOAlwaysOnAudioPanel alloc]initWithStyle:UITableViewStyleInsetGrouped] animated:YES];}
static void AudioMarker(id self,SEL cmd){}
void TIOInstallAlwaysOnAudioMenu(void){Class cls=NSClassFromString(@"TIOLifelogExportsPanel");SEL marker=NSSelectorFromString(@"tio_alwaysOnAudioMenuV1");if(!cls||class_getInstanceMethod(cls,marker))return;Method cell=class_getInstanceMethod(cls,@selector(tableView:cellForRowAtIndexPath:)),footer=class_getInstanceMethod(cls,@selector(tableView:titleForFooterInSection:)),select=class_getInstanceMethod(cls,@selector(tableView:didSelectRowAtIndexPath:));if(!cell||!footer||!select)return;if(!class_addMethod(cls,marker,(IMP)AudioMarker,"v@:"))return;AudioPriorCell=(void *)method_setImplementation(cell,(IMP)AudioCell);AudioPriorFooter=(void *)method_setImplementation(footer,(IMP)AudioFooter);AudioPriorSelect=(void *)method_setImplementation(select,(IMP)AudioSelect);}
#ifdef TIO_AO_AUDIO_HOTLOAD
__attribute__((constructor))static void AudioInstall(void){dispatch_async(dispatch_get_main_queue(),^{if([NSBundle.mainBundle.bundleIdentifier isEqual:@"com.rayneo.venus.pub"]&&[[NSBundle.mainBundle objectForInfoDictionaryKey:@"CFBundleVersion"] isEqual:@"67"])TIOInstallAlwaysOnAudioMenu();});}
#endif
