#import "KnowledgeUI.h"
#import "KnowledgeClient.h"
#import "ResearchUI.h"
UIButton *TIOAgentPicker(void (^changed)(void)){
    UIButton *b=[UIButton buttonWithType:UIButtonTypeSystem];b.showsMenuAsPrimaryAction=YES;UIButtonConfiguration *c=UIButtonConfiguration.tintedButtonConfiguration;c.title=TIOSelectedAgent();c.image=[UIImage systemImageNamed:@"chevron.down"];c.imagePlacement=NSDirectionalRectEdgeTrailing;c.imagePadding=6;c.cornerStyle=UIButtonConfigurationCornerStyleCapsule;b.configuration=c;
    NSMutableArray *actions=[NSMutableArray new];for(NSString *name in @[@"Codex",@"Claude Code",@"Hermes",@"WorkBuddy",@"OpenClaw"]){UIAction *a=[UIAction actionWithTitle:name image:nil identifier:nil handler:^(UIAction *action){[[[NSUserDefaults alloc]initWithSuiteName:@"io.turboio.official-knowledge"] setObject:name forKey:@"agent"];if(changed)changed();}];a.state=[TIOSelectedAgent() isEqual:name]?UIMenuElementStateOn:UIMenuElementStateOff;[actions addObject:a];}b.menu=[UIMenu menuWithTitle:@"Choose Agent" children:actions];[b sizeToFit];return b;
}
@interface TIOKnowledgePanel:UITableViewController
@property(nonatomic) TIOKnowledgeClient *client;
@property(nonatomic) NSDictionary *sources,*job;
@property(nonatomic) NSString *status;
@end
@implementation TIOKnowledgePanel
- (void)viewDidLoad{[super viewDidLoad];self.title=@"Knowledge Base";TIOStyleResearchTable(self);self.job=TIOKnowledgeSnapshot();self.status=@"Your Knowledge Base · Read-only";self.tableView.tableHeaderView=TIOResearchHeader(@"CONNECTED KNOWLEDGE",@"Ask from your Glasses; Codex looks it up.",UIColor.systemTealColor);[self refreshSources];}
- (void)dealloc{[self.client cancel];}
- (void)viewDidDisappear:(BOOL)animated{[super viewDidDisappear:animated];if(!self.navigationController||!self.view.window)[self.client cancel];}
- (void)alert:(NSString *)text{UIAlertController *a=[UIAlertController alertControllerWithTitle:@"Knowledge Base" message:text preferredStyle:UIAlertControllerStyleAlert];[a addAction:[UIAlertAction actionWithTitle:@"OK" style:UIAlertActionStyleCancel handler:nil]];[self presentViewController:a animated:YES completion:nil];}
- (NSInteger)numberOfSectionsInTableView:(UITableView *)t{return 4;}
- (NSInteger)tableView:(UITableView *)t numberOfRowsInSection:(NSInteger)s{return s==0?4:s==1?[self.sources[@"sources"] count]:s==2?2:MAX(1,[self.job[@"results"] count]);}
- (NSString *)tableView:(UITableView *)t titleForHeaderInSection:(NSInteger)s{return @[@"Connection & Access",@"Data Sources",@"Queries & Results",@"Cited Sources"][s];}
- (NSString *)tableView:(UITableView *)t titleForFooterInSection:(NSInteger)s{if(s==0)return @"Only Codex has a connected runner. Other agents can be selected but aren't connected yet. The token is stored in the phone's Keychain.";if(s==1)return @"Queries only data already archived on the Mac. WeChat is not refreshed and live databases are not read. Matching snippets are processed by Codex, and the answer goes to your current Model.";if(s==2)return @"Long queries keep running on the Mac; refresh to see results. This version has no push notifications (APNs), so you may not be notified after leaving.";return nil;}
- (UITableViewCell *)tableView:(UITableView *)t cellForRowAtIndexPath:(NSIndexPath *)ip{
    UITableViewCell *c=[[UITableViewCell alloc]initWithStyle:UITableViewCellStyleSubtitle reuseIdentifier:nil];TIOStyleResearchCell(c);c.textLabel.numberOfLines=0;c.detailTextLabel.numberOfLines=0;c.accessoryType=UITableViewCellAccessoryDisclosureIndicator;
    if(ip.section==0){c.textLabel.text=@[@"Knowledge Base Tool",@"Agent",@"Connection Settings",@"Refresh Status"][ip.row];if(ip.row==0){UISwitch *s=[UISwitch new];s.on=TIOKnowledgeEnabled();[s addTarget:self action:@selector(toggle:) forControlEvents:UIControlEventValueChanged];c.accessoryView=s;c.detailTextLabel.text=@"Allow voice queries to the read-only Knowledge Base";}if(ip.row==1){__weak typeof(self) weak=self;c.accessoryView=TIOAgentPicker(^{[weak.tableView reloadData];});c.detailTextLabel.text=[TIOSelectedAgent() isEqual:@"Codex"]?@"Codex App Server · runs on Mac":@"No runner connected";}if(ip.row==2)c.detailTextLabel.text=TIOKnowledgeEndpoint().length?TIOKnowledgeEndpoint():@"Set HTTPS Endpoint and dedicated token";if(ip.row==3)c.detailTextLabel.text=self.status;}
    else if(ip.section==1){NSDictionary *s=self.sources[@"sources"][ip.row];c.textLabel.text=s[@"name"];c.detailTextLabel.text=[NSString stringWithFormat:@"%@ · %@ items\nUpdated: %@\n%@%@",[s[@"available"] boolValue]?@"Available":@"Unavailable",s[@"count"]?:@0,s[@"updatedAt"]?:@"Unknown",s[@"scope"]?:@"",[s[@"partial"] boolValue]?@"\nScope limited or files skipped":@""];c.accessoryType=UITableViewCellAccessoryNone;}
    else if(ip.section==2){c.textLabel.text=ip.row==0?@"New Query":@"Refresh Latest Result";c.detailTextLabel.text=ip.row==0?@"e.g. What's new with a project in WeChat?":[NSString stringWithFormat:@"%@\n%@",self.job[@"status"]?:@"No queries yet",self.job[@"answer"]?:self.job[@"error"]?:@""];}
    else {NSArray *r=self.job[@"results"];if(!r.count){c.textLabel.text=@"No Citations";c.detailTextLabel.text=@"Sources appear after a query finishes.";}else{NSDictionary *e=r[ip.row];c.textLabel.text=e[@"title"];c.detailTextLabel.text=[NSString stringWithFormat:@"%@ · %@\n%@",e[@"sourceLabel"]?:@"",e[@"messageAt"]==NSNull.null?e[@"updatedAt"]:e[@"messageAt"]?:e[@"updatedAt"],e[@"excerpt"]?:@""];}c.accessoryType=UITableViewCellAccessoryNone;}return c;
}
- (void)toggle:(UISwitch *)s{TIOSetKnowledgeEnabled(s.on);if(s.on&&!TIOKnowledgeEnabled()){s.on=NO;[self alert:@"Set up the connection and choose Codex first."];}}
- (void)refreshSources{[self.client cancel];self.client=[TIOKnowledgeClient new];self.status=@"Connecting…";__weak typeof(self) weak=self;[self.client sources:^(NSDictionary *j,NSString *e){weak.sources=j;weak.status=e?:@"Mac service connected · Codex starts per query";[weak.tableView reloadData];}];}
- (void)configure{UIAlertController *a=[UIAlertController alertControllerWithTitle:@"Knowledge Base Connection" message:@"Private HTTPS gateway. The token isn't shown; leave it blank to keep the current one." preferredStyle:UIAlertControllerStyleAlert];[a addTextFieldWithConfigurationHandler:^(UITextField *f){f.text=TIOKnowledgeEndpoint();f.placeholder=@"https://…/api/turbo-knowledge";f.autocapitalizationType=UITextAutocapitalizationTypeNone;}];[a addTextFieldWithConfigurationHandler:^(UITextField *f){f.placeholder=@"Dedicated connection token";f.secureTextEntry=YES;}];[a addAction:[UIAlertAction actionWithTitle:@"Cancel" style:UIAlertActionStyleCancel handler:nil]];[a addAction:[UIAlertAction actionWithTitle:@"Save" style:UIAlertActionStyleDefault handler:^(UIAlertAction *x){BOOL ok=TIOConfigureKnowledge(a.textFields[0].text,a.textFields[1].text);a.textFields[1].text=@"";if(ok)[self refreshSources];else [self alert:@"Invalid Endpoint or token. Not saved."]; }]];[self presentViewController:a animated:YES completion:nil];}
- (void)tableView:(UITableView *)t didSelectRowAtIndexPath:(NSIndexPath *)ip{[t deselectRowAtIndexPath:ip animated:YES];if(ip.section==0){if(ip.row==2)[self configure];if(ip.row==3)[self refreshSources];return;}if(ip.section!=2)return;
    if(ip.row==1){[self.client cancel];self.client=[TIOKnowledgeClient new];__weak typeof(self) weak=self;[self.client refreshLast:^(NSDictionary *j,NSString *e){if(j)weak.job=j;if(e)[weak alert:e];[weak.tableView reloadData];}];return;}
    UIAlertController *a=[UIAlertController alertControllerWithTitle:@"Ask Codex" message:@"Searches archived data only. Nothing is written." preferredStyle:UIAlertControllerStyleAlert];[a addTextFieldWithConfigurationHandler:^(UITextField *f){f.placeholder=@"Enter your question";}];[a addAction:[UIAlertAction actionWithTitle:@"Cancel" style:UIAlertActionStyleCancel handler:nil]];[a addAction:[UIAlertAction actionWithTitle:@"Search" style:UIAlertActionStyleDefault handler:^(UIAlertAction *x){NSString *q=a.textFields[0].text?:@"";if(q.length<2||q.length>200){[self alert:@"Enter 2 to 200 characters."];return;}[self.client cancel];self.client=[TIOKnowledgeClient new];self.job=@{@"status":@"Searching…"};[self.tableView reloadData];__weak typeof(self) weak=self;[self.client query:@{@"query":q,@"source":@"all"} completion:^(NSDictionary *j,NSString *e){if(j)weak.job=j;if(e)[weak alert:e];[weak.tableView reloadData];}];}]];[self presentViewController:a animated:YES completion:nil];
}
@end
void TIOOpenKnowledge(UIViewController *host){[host.navigationController pushViewController:[[TIOKnowledgePanel alloc]initWithStyle:UITableViewStyleInsetGrouped] animated:YES];}
