#import "ProfileUI.h"
#import "Profile.h"
@interface TIOProfilePanel:UIViewController
@property(nonatomic) UITextField *nameField,*identityField;
@property(nonatomic) UITextView *preferences;
@end
@implementation TIOProfilePanel
- (void)viewDidLoad{[super viewDidLoad];self.title=@"Profile & Prompt";self.view.backgroundColor=UIColor.systemGroupedBackgroundColor;
    self.navigationItem.rightBarButtonItem=[[UIBarButtonItem alloc]initWithTitle:@"Save" style:UIBarButtonItemStyleDone target:self action:@selector(save)];
    UIScrollView *scroll=[UIScrollView new];scroll.translatesAutoresizingMaskIntoConstraints=NO;scroll.keyboardDismissMode=UIScrollViewKeyboardDismissModeInteractive;[self.view addSubview:scroll];
    UIStackView *stack=[UIStackView new];stack.axis=UILayoutConstraintAxisVertical;stack.spacing=14;stack.translatesAutoresizingMaskIntoConstraints=NO;[scroll addSubview:stack];
    [NSLayoutConstraint activateConstraints:@[[scroll.topAnchor constraintEqualToAnchor:self.view.safeAreaLayoutGuide.topAnchor],[scroll.leadingAnchor constraintEqualToAnchor:self.view.leadingAnchor],[scroll.trailingAnchor constraintEqualToAnchor:self.view.trailingAnchor],[scroll.bottomAnchor constraintEqualToAnchor:self.view.keyboardLayoutGuide.topAnchor],[stack.topAnchor constraintEqualToAnchor:scroll.contentLayoutGuide.topAnchor constant:20],[stack.leadingAnchor constraintEqualToAnchor:scroll.contentLayoutGuide.leadingAnchor constant:20],[stack.trailingAnchor constraintEqualToAnchor:scroll.contentLayoutGuide.trailingAnchor constant:-20],[stack.bottomAnchor constraintEqualToAnchor:scroll.contentLayoutGuide.bottomAnchor constant:-24],[stack.widthAnchor constraintEqualToAnchor:scroll.frameLayoutGuide.widthAnchor constant:-40]]];
    NSDictionary *p=TIOProfile();NSArray *labels=@[@"Name (max 80 characters)",@"Identity & Background (max 500 characters)",@"Answer Preferences / Extra Prompt (max 2000 characters)"];
    for(NSUInteger i=0;i<3;i++){UILabel *label=[UILabel new];label.text=labels[i];label.font=[UIFont preferredFontForTextStyle:UIFontTextStyleHeadline];[stack addArrangedSubview:label];
        if(i<2){UITextField *field=[UITextField new];field.borderStyle=UITextBorderStyleRoundedRect;field.font=[UIFont preferredFontForTextStyle:UIFontTextStyleBody];field.text=p[i?@"identity":@"name"];field.placeholder=i?@"e.g. Software developer interested in AI":@"How the AI should address you";[field.heightAnchor constraintGreaterThanOrEqualToConstant:48].active=YES;[stack addArrangedSubview:field];if(i)self.identityField=field;else self.nameField=field;}
        else{self.preferences=[UITextView new];self.preferences.font=[UIFont preferredFontForTextStyle:UIFontTextStyleBody];self.preferences.backgroundColor=UIColor.secondarySystemGroupedBackgroundColor;self.preferences.layer.cornerRadius=12;self.preferences.textContainerInset=UIEdgeInsetsMake(12,12,12,12);self.preferences.text=p[@"preferences"];[self.preferences.heightAnchor constraintEqualToConstant:200].active=YES;[stack addArrangedSubview:self.preferences];}
    }
    UILabel *note=[UILabel new];note.numberOfLines=0;note.font=[UIFont preferredFontForTextStyle:UIFontTextStyleFootnote];note.textColor=UIColor.secondaryLabelColor;note.text=@"All fields are empty by default. Saved changes apply from the next own-model chat and do not change the official model.\nThis profile is stored in local settings and sent with each chat to the model service you configured. Do not enter API keys, passwords or anything private you do not want uploaded.\nClear the fields and save to restore the defaults. Going back without saving leaves settings unchanged.";[stack addArrangedSubview:note];
}
- (void)save{BOOL ok=TIOSaveProfile(@{@"name":self.nameField.text?:@"",@"identity":self.identityField.text?:@"",@"preferences":self.preferences.text?:@""});if(ok){[self.view endEditing:YES];[self.navigationController popViewControllerAnimated:YES];}else{UIAlertController *a=[UIAlertController alertControllerWithTitle:@"Not Saved" message:@"Check the length and remove invisible control characters." preferredStyle:UIAlertControllerStyleAlert];[a addAction:[UIAlertAction actionWithTitle:@"OK" style:UIAlertActionStyleCancel handler:nil]];[self presentViewController:a animated:YES completion:nil];}}
@end
void TIOOpenProfile(UIViewController *host){[host.navigationController pushViewController:[TIOProfilePanel new] animated:YES];}
