#import <UIKit/UIKit.h>
#import "ResearchUI.h"
#import <objc/runtime.h>
#import "RecordingExports.h"
@interface TIORecordingExportsPanel:UITableViewController<UIDocumentPickerDelegate>
@property(nonatomic) NSArray<NSDictionary *> *audio;
@property(nonatomic) BOOL busy;
@end
@implementation TIORecordingExportsPanel
- (void)viewDidLoad{[super viewDidLoad];self.title=@"Share Recordings & Text";self.navigationItem.rightBarButtonItem=[[UIBarButtonItem alloc]initWithBarButtonSystemItem:UIBarButtonSystemItemRefresh target:self action:@selector(refresh)];[self refresh];}
- (void)refresh{if(self.busy)return;self.busy=YES;dispatch_async(dispatch_get_global_queue(QOS_CLASS_UTILITY,0),^{NSArray *rows=TIOPreparedAudioFiles([NSURL fileURLWithPath:NSHomeDirectory()]);dispatch_async(dispatch_get_main_queue(),^{self.audio=rows;self.busy=NO;[self.tableView reloadData];});});}
- (NSInteger)numberOfSectionsInTableView:(UITableView *)t{return 2;}
- (NSInteger)tableView:(UITableView *)t numberOfRowsInSection:(NSInteger)s{return s==0?MAX(1,self.audio.count):1;}
- (NSString *)tableView:(UITableView *)t titleForHeaderInSection:(NSInteger)s{return s==0?@"Prepared Audio on This Phone":@"Markdown Text";}
- (NSString *)tableView:(UITableView *)t titleForFooterInSection:(NSInteger)s{return s==0?@"First, in the official recording details, tap Share → Audio to generate the format you need. Generated files are listed here but not matched to the current recording, so check the name and time. Tap a file to share a separate copy via AirDrop or Save to Files. No public link is created and the original recording is not deleted.":@"Reading the full transcript of the current recording isn't available yet. Import an existing full TXT/MD file to create Markdown. Visible on-screen snippets are never treated as the full text.";}
- (UITableViewCell *)tableView:(UITableView *)t cellForRowAtIndexPath:(NSIndexPath *)ip{UITableViewCell *c=[[UITableViewCell alloc]initWithStyle:UITableViewCellStyleSubtitle reuseIdentifier:nil];TIOStyleResearchCell(c);c.detailTextLabel.numberOfLines=0;if(ip.section==1){c.textLabel.text=@"Import TXT/MD and Share Markdown";c.accessoryType=UITableViewCellAccessoryDisclosureIndicator;}else if(!self.audio.count){c.textLabel.text=self.busy?@"Reading local files…":@"No Prepared Audio";c.selectionStyle=UITableViewCellSelectionStyleNone;}else{NSDictionary *row=self.audio[ip.row];c.textLabel.text=row[@"name"];c.textLabel.numberOfLines=2;NSDateFormatter *fmt=[NSDateFormatter new];fmt.dateFormat=@"MM-dd HH:mm";c.detailTextLabel.text=[NSString stringWithFormat:@"%@ · %@",[fmt stringFromDate:row[@"date"]],[NSByteCountFormatter stringFromByteCount:[row[@"bytes"] longLongValue] countStyle:NSByteCountFormatterCountStyleFile]];c.accessoryType=UITableViewCellAccessoryDisclosureIndicator;}return c;}
- (void)showError:(NSString *)message{UIAlertController *a=[UIAlertController alertControllerWithTitle:@"Not Shared" message:message preferredStyle:UIAlertControllerStyleAlert];[a addAction:[UIAlertAction actionWithTitle:@"OK" style:UIAlertActionStyleCancel handler:nil]];[self presentViewController:a animated:YES completion:nil];}
- (void)share:(NSURL *)file{UIActivityViewController *sheet=[[UIActivityViewController alloc]initWithActivityItems:@[file] applicationActivities:nil];sheet.popoverPresentationController.sourceView=self.view;sheet.popoverPresentationController.sourceRect=CGRectMake(self.view.bounds.size.width/2,100,1,1);[self presentViewController:sheet animated:YES completion:nil];}
- (void)tableView:(UITableView *)t didSelectRowAtIndexPath:(NSIndexPath *)ip{[t deselectRowAtIndexPath:ip animated:YES];if(self.busy)return;if(ip.section==1){UIDocumentPickerViewController *p=[[UIDocumentPickerViewController alloc]initWithDocumentTypes:@[@"public.plain-text",@"net.daringfireball.markdown"] inMode:UIDocumentPickerModeImport];p.delegate=self;p.allowsMultipleSelection=NO;[self presentViewController:p animated:YES completion:nil];return;}if(ip.row>=self.audio.count)return;NSURL *source=self.audio[ip.row][@"url"];self.busy=YES;dispatch_async(dispatch_get_global_queue(QOS_CLASS_UTILITY,0),^{NSError *error=nil;NSURL *file=TIOAudioShareCopy([NSURL fileURLWithPath:NSHomeDirectory()],source,&error);dispatch_async(dispatch_get_main_queue(),^{self.busy=NO;if(file)[self share:file];else [self showError:error.localizedDescription];});});}
- (void)documentPicker:(UIDocumentPickerViewController *)p didPickDocumentsAtURLs:(NSArray<NSURL *> *)urls{NSURL *url=urls.firstObject;if(!url)return;self.busy=YES;dispatch_async(dispatch_get_global_queue(QOS_CLASS_UTILITY,0),^{NSError *error=nil;NSNumber *size=nil;[url getResourceValue:&size forKey:NSURLFileSizeKey error:&error];NSString *text=nil;if(size&&size.unsignedLongLongValue<=8*1024*1024)text=[NSString stringWithContentsOfURL:url encoding:NSUTF8StringEncoding error:&error];NSURL *file=text?TIOMarkdownShareFile([NSURL fileURLWithPath:NSHomeDirectory()],url.lastPathComponent.stringByDeletingPathExtension,text,&error):nil;dispatch_async(dispatch_get_main_queue(),^{self.busy=NO;if(file){if(self.presentedViewController)[self dismissViewControllerAnimated:YES completion:^{[self share:file];}];else [self share:file];}else [self showError:@"Only complete UTF-8 text files are supported (up to 8 MB / 2,000,000 characters). Official history was not read."];});});}
@end
